<Project>

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AnalysisMode>Recommended</AnalysisMode>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup>
		<Version>2.0.0-beta.0.1</Version>
		<Authors>Pablo Belin</Authors>
		<Title>GG.Net Data Visualization</Title>
		<Copyright>Copyright (c) 2020-2026 Pablo Belin</Copyright>
		<Description>GG.Net lets Data Scientists and Developers create flexible charts for .Net in C# and F#</Description>
		<PackageTags>plotting;plot;plots;charting;chart;charts;visualization;ML.Net;csharp;fsharp;blazor;geospacial</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/pablofrommars/GGNet</PackageProjectUrl>
		<RepositoryUrl>https://github.com/pablofrommars/GGNet</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

</Project>
