<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageDescription>GG.Net Data Visualization Static Rendering</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GGNet.Headless.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="11.0.0-preview.6.26359.118" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../GGNet/GGNet.csproj" />
  </ItemGroup>

</Project>
